name: Build Release

on: 
  workflow_dispatch:

env:
  DEPOT_DOWNLOADER_VERSION: 2.5.0
  A_PUBLICIZER_VERSION: 1.0.3
  SL_REFERENCES: "${{ github.workspace }}/References/SCPSL_Data/Managed"
  UNITY_REFERENCES: "${{ github.workspace }}/References/SCPSL_Data/Managed"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      releasePath: "${{ github.workspace }}"
    steps:
    - name: Checkout main repository.
      uses: actions/checkout@v4
    - name: Download depot downloader
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path ${{ github.workspace }}/DepotDownloader
        Invoke-WebRequest -Uri "https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_${{ env.DEPOT_DOWNLOADER_VERSION }}/DepotDownloader-linux-x64.zip" -OutFile "${{ github.workspace }}/depotdownloader.zip"
        Expand-Archive -Path ${{ github.workspace }}\depotdownloader.zip -PassThru -DestinationPath ${{ github.workspace }}/DepotDownloader
        New-Item -ItemType Directory -Force -Path ${{ github.workspace }}/References
    - name: Download SCPSL Refs
      run: |
        chmod 777 ${{ github.workspace }}/DepotDownloader/DepotDownloader
        chmod 777 ${{ github.workspace }}/References
        ${{ github.workspace }}/DepotDownloader/DepotDownloader -app 996560 -os windows -dir "${{ github.workspace }}/References" -filelist "${{ github.workspace }}/download-files.txt"
    - name: Download APublicizer
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path ${{ github.workspace }}/APublicizer
        Invoke-WebRequest -Uri "https://github.com/iRebbok/APublicizer/releases/download/${{ env.A_PUBLICIZER_VERSION }}/native-linux-x64-release.tar.gz" -OutFile "${{ github.workspace }}/apub.tar.gz"
        Expand-Archive -Path ${{ github.workspace }}\apub.tar.gz -PassThru -DestinationPath ${{ github.workspace }}/APublicizer
    - name: Publicize Assemblies
      run: |
        chmod 777 ${{ github.workspace }}/APublicizer
        ${{ github.workspace }}/APublicizer/APublicizer "${{ env.SL_REFERENCES }}/Assembly-CSharp.dll"
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build --configuration Release
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Agents
        path: ${{ github.workspace }}/Agents/bin/Release/net48/Agents.dll
    - name: Get Release Info
      id: release-info
      uses: zoexx/github-action-json-file-properties@b9f36ce6ee6fe2680cd3c32b2c62e22eade7e590
      with: 
          file_path: "${{ env.releasePath }}/releaseInfo.json"
    - name: Set Environment Variables
      run: |
        echo "version=${{ steps.release-info.outputs.version }}" >> $GITHUB_ENV
    - name: Create Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: ""
        custom_tag: "${{ env.version }}"
    - name: Make Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
      with:
        files: |
          ${{ github.workspace }}/Agents/bin/Release/net48/Agents.dll
          ${{ env.releasePath }}/releaseInfo.json
        tag_name: ${{ env.version }}
